### ISSUE TITLE
No feasible way to call Apps.update after changing GameModel [...]

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#107]
### No feasible way to call Apps.update after changing `GameModel` or... 

# Discussion: How `Game` should affect `Apps`

<br/>

I've found a problem while designing/planning the models of the `DesktopManager` (aka `Workspaces`), I'll try to be as didactic as possible now...

As of #103, we forbid `Game -> App` communication, right? Tons of advantages, simplifies things a lot and etc but...

<br/>

> **There's no way to reliably update an `App` `model` after updating the `Game` `model`.**

---

<br/>

`<assumptions>`
Ideally, we want to `update` our `Apps` `model` after changing the `Game` `model`.
`</assumptions>`

<br/>

To make this happen, we have to do this flux:

```elm
    every GameModel.update
    calls Apps.update
```

<br/>

It's not possible to do this flow right now for two main reasons:

1. There's no way to create a global message `GameUpdate` and pass it forward to the `Apps`, so using message based solutions requires adding tons of boilerplate. :disappointed: 
2. There's no `App` function to sync apps with the `GameModel`.

There is three main solutions for that:
<br/>

1. Adding a `GameUpdateMsg` to each `App` model.
    - **PROS:** No need to add another function to manage `Game` `model`.
    - **CONS:** Extra message boilerplate for every `App` (and also `OS`).
<br/>

2. Adding an extra function that receives the `GameModel` without any message.
    - **PROS:** A lot less boilerplate on fathers.
    - **CONS:** One more `API` function, more boilerplate on `Apps`.
<br/>

3. Forbid any `App` `model` `update` based on `GameModel`, removing `GameModel` param from `Apps` `update` function
    - **PROS:** No extra boilerplate, `Apps` will just contain `UI` state. (separation of concerns)
    - **CONS:** Opinionated (_technically this could be actually a pro_), less flexibility, may (or not) require moving more state to `Game`.

<br/>

~~Obviously I'm a fan of the 3rd solution :smile: , but it might be the wrong solution for us, it's too much opinionated.~~ (actually the 3rd solution introduces heavy overhead unless we use an app cache system within Game, so I'm not liking this solution anymore)
<br/>

> Note: Maybe this whole issue is no surprise, maybe we don't want to keep any state references to
> anything on `GameModel`, but these are just assumptions, I'm not sure of anything.

<br/>

The most important to think is: **What we decide now will change how we design every `App` `models`.**

<br/>

---

**NOTE:** Everyone is assigned for discussion, but I'll be the one who will fix it

**Comment by kress95** [comment]
I've changed my opinion regarding the 3rd solution after a recent talk with @PedroHLC.
Now I'm more geared toward a variant of the 2nd solution, it would work as a per App game cache (App type, not instance).

**Comment by renatomassaro** [comment]
As we've discussed, we'll probably stick to the first solution.

Once game model is updated, we'll go through a function within the Game context which will filter the change and, based on what changed, see if it will emit a `GameModelChanged` message. 

The `GameModelChanged` message is broadcasted to all Apps, similar to the `MenuMsg` one. It's up to the app to see if the Model change is relevant to it or not, updating the model (if it's relevant) or performing a no-op (if it isn't).

**Comment by kress95** [comment]
I'm back here to propose the final solution to this mess:

---

- Keep `Game.Model` available for every function, but you should never copy this data to application's model, it's only passed because it's useful for command composition and because it contains other useful data (such as current time).

- On 99% of the cases, use and process `Game.Model` on the view function without any fear of performance loss, we'll use [Html.Lazy](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Lazy) to optimize that, performance won't ever be a problem.

---

That's it, no `Game -> App` communication is needed, `Game.Model` behaves like a single source of truth, it's never copied anywhere (no syncing is needed, yay 😄 ) and performance won't suffer from that.

> `10/10 solution, minimal overhead from extra lambdas, but tons of advantages`

Our architecture is not be the easiest to work with, 100% fractal structure was a mistake (quoting [Feldman](https://groups.google.com/d/msg/elm-discuss/Lo6bG96zotI/0ak6T2DaDgAJ) and fake-quoting Miyazaki), we can't fix that now, but we're able to avoid making it worse.

---

I'll close the issue but feel free to discuss.
