### ISSUE TITLE
Proposal: change expose/import name conventions

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#109]
We're currently using a import/expose convention that looks like that:

```elm
module OS.Messages exposing (OSMsg(..))

import OS.WindowManager.Messages

type OSMsg
    = MsgWM OS.WindowManager.Messages.WMMsg
```

I propose changing it into that:

```elm
module OS.Messages exposing (Msg(..))

import OS.WindowManager.Messages as WM

type Msg
    = WMMsg WM.Msg
```

### Why?

`*.Messages`, `*.Models`, `*.Subscriptions`, `*.Update` and `*.View` are parts of the same `*`, I believe that they were split to make things easier on eyes and to reduce compiler stress when changing minor things, so it may make some sense to join them when accessing from the outside.

Elm allows importing multiple modules under the same alias, and it will trigger warnings on name collisions, but this is not even a problem because:

- `Messages` just exposes Msg types;
- `Subscriptions` just exposes one function;
- `Update` just exposes one function;
- `View` may expose many functions, but usually just `view`, additional functions could get a "view" prefix to avoid collisions;
- Models expose many types and functions, but they should not collide with the previous modules unless we do something really bad;

Another thing is that this change reduces some cognitive load.

**Comment by renatomassaro** [comment]
As discussed, we'll adopt the proposed standard once all major PRs are merged.
