### ISSUE TITLE
Apps subscriptions are broken

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#111]
This is a side-effect of #107. Solving it is required before solving this one.
Before 1b4806b2962e8f2938ed1403e25145ed12592ba4, Core [used to](https://github.com/HackerExperience/HEBorn/blob/66cb67c33ac94f20d62d5c6121e06f57ff0bbbf1/src/Core/Subscriptions.elm#L17) subscribe all apps using a `MsgApp`. Now, apps subscriptions are waiting their own model and their subscriptions are broken.
FYI: The only subscription we are using in apps right now is the one which propagates ContextMenu events (like closing it).

**Comment by kress95** [comment]
> Hmm, I'm not sure this should've been an issue, issues are usually related to master code, but whatever...

This is related to PR #103, and this PR is being closed in favor to PR #106 which has this problem fixed.

I'm closing this now. :+1:
