### ISSUE TITLE
The "Wrong password/username" dont work

### ISSUE THREAD

**Issue by marius851000** [HackerExperience/HEBorn#117]
I've tested on chrome and firefox, there are no message like wrong password/username.

**Comment by kress95** [comment]
I've added some notes about it at #120, I'll try to fix this there.

**Comment by kress95** [comment]
Login was easily fixed (I'll close this once I merge it).

Signing up is a bit more complex and should be delayed (the whole signup code needs to be remade to work properly with server side errors).
