### ISSUE TITLE
Rename `make setup` to `make install`

### ISSUE THREAD

**Issue by mememori** [HackerExperience/HEBorn#124]
Seriously

**Comment by renatomassaro** [comment]
It was `make install` before, but this could lead the user to think she should run `./configure` and `make` before, as is the usual make process.

`make setup` leaves no room for this kind of confusion.

**Comment by PedroHLC** [comment]
What about `make prepare` ?

**Comment by mememori** [comment]
What about `make us harder better faster stronger` ?

**Comment by renatomassaro** [comment]
I'd prefer `make america great again` :tipping_hand_woman:

**Comment by mememori** [comment]
Please `sudo systemctl stop trumpjokes`

**Comment by kress95** [comment]
B-but Renato doesn't use systemd :joy:

**Comment by PedroHLC** [comment]
I don't believe systemd is even here nowadays...

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
