### ISSUE TITLE
Heborn.OS don't start when Helix sends invalid bootstrap

### ISSUE THREAD

**Issue by marius851000** [HackerExperience/HEBorn#209]
I have any error : I connect to my account, but, avec choose my loacation and finish the setup, the game screen is blank.
( mozilla nightly and microsoft edge tested )
![image](https://user-images.githubusercontent.com/22586596/29624064-7ca67fc8-8828-11e7-8c4a-73fee66faefa.png)
error in the console
![image](https://user-images.githubusercontent.com/22586596/29624136-a1e98672-8828-11e7-89ab-3a46997b2850.png)

**Comment by kress95** [comment]
Thanks for your effort of opening an issue for that, we're already aware of the issue and will fix that ASAP.

[![image](https://user-images.githubusercontent.com/2013206/29629375-ec222aa6-880e-11e7-8733-ffac0517b5d5.png)](https://discord.gg/keCWy67)

(click the image to go to our discord server)

**Comment by marius851000** [comment]
OK, thank.

**Comment by Jark255** [comment]
I have the same problem. When I tried to check the link in the error, I saw "Invalid API key" error.
![2017-08-31 18 35 27](https://user-images.githubusercontent.com/26852786/29932176-2fcddd36-8e7c-11e7-94dd-67acd5a63354.png)

**Comment by PedroHLC** [comment]
So, this will be closed when [Helix/#253](https://github.com/HackerExperience/Helix/issues/253) is closed

@Jark255 that's actually another bug, we're aware of it

**Comment by PedroHLC** [comment]
This was promoted to `ERR_PORRA_RENATO` that indicates Helix bootstrap account response is different from what HEBorn is expecting.
