### ISSUE TITLE
Join server request and event

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#229]
-	Join request
	-	[ ] Encoder (ip, psw, browser window id, browser tab id)
	-	[ ] Send request
-	Joined event
	-	[ ] Decoder
	-	[ ] Dispatch event
	-	[ ] Add to endpoint list and set active (without changing active context)
-	Browser adjusts
	-	[ ] `Pages.{Default,Custom} ` adjusts
		- funtion to check if endpoint already connected
		- unlogged state on model
		- When connected and not unlogged: Show admin options
		- When not: Show webserver

Depends on #227

**Comment by kress95** [comment]
Forgot to edit this to reflect changes on #241, many invalid tasks here the only one not done is the last one (Browser adjusts)

**Comment by kress95** [comment]
Done.
