### ISSUE TITLE
Better Websocket Reports

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#239]
I better analyzed our Drivers and the Phoenix Channels library and discovered some amazing things:

We don't need ANY bootstrap request, we're able to receive values back from:

- `onJoin`
- `onJoinError`
- `onRejoin`
- `onLeave`
- `onLeaveError` (It seems that Phoenix v1.2 doesn't send this)

Account `onJoin` could return the server list and account information.

And then we use the `onJoin` to bootstrap every server and `onJoinError` to report wrong passwords/server not accessible...

**Comment by PedroHLC** [comment]
nice :blush:

**Comment by PedroHLC** [comment]
nice :blush:

**Comment by PedroHLC** [comment]
nice :blush:

**Comment by kress95** [comment]
Done some weeks ago
