### ISSUE TITLE
Integrate Storyline

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#261]

**Comment by kress95** [comment]
Halfway done at #257 (already on bootstrap).

**Comment by PedroHLC** [comment]
via Hubstaff
User: Pedro Henrique Lara Campos

Project: HEBorn - https://app.hubstaff.com/projects/215015
Date Range: 10/05/17 - 10/06/17
Work session total: 8:47:41

Grand total: 8:47:41
