### ISSUE TITLE
Implement Core Crash State

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#267]
Instead of crashing the entire elm app, throw the player to a BSOD screen

![](http://cdn.overclock.net/6/61/619ca210_This-Could-Be-Windows-10-s-BSOD-If-Microsoft-Had-a-Sense-of-Humor-477814-2.jpeg)

*NOTE*: Maybe Debug.crash must be rewritten in JS to throw a Model to Core instead

**Comment by kress95** [comment]
I'll remove the chore tag 'cause this is a fun task :T
