### ISSUE TITLE
Do not show gateway/endpoint toggle when no endpoint is selected

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#321]
Affects: Window Manager

**Comment by themaxhero** [comment]
Closed by #341

**Comment by themaxhero** [comment]
via Hubstaff
User: Marcelo Amancio de Lima Santos

Project: HEBorn - https://app.hubstaff.com/projects/215015
Date Range: 12/13/17 - 12/14/17
Work session total: 2:46:18

Grand total: 2:46:18
