### ISSUE TITLE
Proper notifications 

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#327]
The way some notifications are being launched now makes no sense, most notifications should be evenly displayed on every tab the game is opened, so we should restrict ourselves to launch notifications upon receiving events, not when doing requests or receiving request responses.

Some offenders are `NewDownloadProcess` and `NewPublicDownloadProcess` dispatchs, we should improve/create the `StartedProcess` and push these notifications from it.

Another thing to note is that when a notification is conditionally launched, it shouldn't be pushed from `Subscribers`, do not put error prone code into it, it should be as safe as possible, it's currently the core of the game.

To make things less verbose, I'm experimenting with simple data extraction helpers for building simple notifications, like this one for `NewEmail`:

```elm
notify : (String -> value) -> (Maybe Float -> value -> msg) -> Data -> msg
notify toContent toMsg { personId, messageNode } =
    let
        ( time, _ ) =
            messageNode
    in
        toMsg (Just time) <| toContent personId
```

And using it like:

```elm
fromEmails : Emails -> Subscribers
fromEmails dispatch =
    case dispatch of
        ReplyEmail a ->
            [ emails <| Emails.HandleReply a ]

        ReceivedEmail a ->
            [ emails <| Emails.HandleNewEmail a
            , accountNotif <|
                StoryNewEmail.notify Notifications.NewEmail
                    Notifications.HandleInsert
                    a
            ]

        UnlockedEmail a ->
            [ emails <| Emails.HandleReplyUnlocked a ]
```

You could even go as far as making this function return Notifications.NewEmail instead of expecting it as a param, I didn't do that to avoid imports.

**Comment by PedroHLC** [comment]
@kress95 was this solved?

**Comment by kress95** [comment]
Nope, people are trying to crack the Download Center in production and it's starting an optimistic process.
