### ISSUE TITLE
Dock decoder is not used anywhere

### ISSUE THREAD

**Issue by themaxhero** [HackerExperience/HEBorn#373]
I've realized today that Decoders.Dock isn't used anywhere, so we should remove it.

**Comment by PedroHLC** [comment]
I do believe @kress95  wanted can be used in the future, for customization or making elements disappear/appear on server-side...

**Comment by kress95** [comment]
Yup, it's purpose is allowing dock icon reordering, not really implemented, but surely will (low priority feature).
