### ISSUE TITLE
Forbid importing */Models.elm when hierarchy doesn't enforce it 

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#392]
When having to import a */Model.elm that isn't enforced by hierarchy, move the needed type to a Shared.elm and import it instead.

Sometimes it may even be sensitive to just repeat the type annotation instead of importing the type, code sharing between domains should be handled carefully.

Reasoning: each TEA structure should be considered a different App with integration dictated by Config, depending on other App's implementation code shouldn't happen, consider that the Shared file is like a C Header.

**Comment by PedroHLC** [comment]
Thought of that in the way to the office today.
Before config I would also recommend using Shared instead of Models in Messages so that people importing Messages don't fall into the import chain...

**Comment by kress95** [comment]
The idea is that things importing Shared won't be recompiled when changing model, but when changing shared everyone is f*cked, this is the general idea behind the "new" shared.

**Comment by kress95** [comment]
After using the `Config` pattern for a while, it became clear that this rule only applies to the local domain:

**While in OS, one shouldn't import the model of a sibling or cousing OS model, but there's no problem in importing a `Game`model.**

This shouldn't be a issue, but something documented somewhere.
