### ISSUE TITLE
WindowManager tech debts

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#444]
Our main problems now are pretty low priority, but I'll enumerate them here to avoid future gotchas.

### We're storing Applications at Game to avoid the "Game depends on OS" problem

Fixing that is possible if we:

- Stop using DesktopApp and start using Strings to store Dock app order;
- Stop using Requester type for Game.Web communication;
- Stop using Reference type (or start using a plain String) for Game communication;

### Endpoint-only windows have no access to a gateway

This is not a problem because we have no endpoint-only windows, ways to fix it are:

- **A)** Getting a gateway from Config;
- **B)** Inspecting config.servers to find the active gateway for that window CId;

### Adding apps is tedious again

Adding apps requires too many places to touch:

- 1) Edit `OS.WindowManager.Models`.
- 2) Edit `OS.WindowManager.Messages`.
- 3) Edit delegates at `OS.WindowManager.Launch`, `OS.WindowManager.Update` and `OS.WindowManager.View`.
- 4) Edit `Game.Meta.Types.Apps.Desktop`.
- 5) Edit `OS.WindowManager.Subscriptions` when app has subscriptions.
- 6) Edit `Apps.Params` when app has params.
- 7) Update functions at `Apps.Shared`.

The first 4 items are impossible to avoid changing.

Items 5 and 6 are optional, only apps with subscriptions or initialization params may need them.

7 is the rage spot, I'm not happy with how it works, but I don't know a proper solution for that.

### I'm still not happy with our Launch.elm

And I'm probably pushing myself too hard over it.

**Comment by PedroHLC** [comment]
Notes:
1 - I would never put Apps in Game, that is kind of confusing as it implicates Apps is somehow a sub component of Game, which it isn't! Yes, we should stop using this types, for when referencing an app in callbacks signatures, we should somehow use an instance id (which I expect is a String), Bool for context, String/Int for tabs, no need for using types from Apps.
DesktopApp should be in Core, and though this would only complicate things, the best would be for Core to handle Apps, passing to WindowManager things like "initialModel, update, subscription, view", this way, we would have OS and Apps fully independent from each other, but again, that would be a huge pain in the ass...
2 - We used to pass "activeGateway" and we could pass "gateways" through configs to apps, why isn't this happening anymore?
3 - If you're sure that is the best way, OK!

**Comment by kress95** [comment]
### We're storing Applications at Game to avoid the "Game depends on OS" problem

> DesktopApp should be in Core

Just caught another problem in our codebase, both `Game` and `OS` code depending on `Core.Flags` and `Core.Error`, we should figure what to do about them, no one should import anything from Core...

> would have OS and Apps fully independent from each other, but again, that would be a huge pain in the ass...

Yes, this is a PITA to do, moving that's not worth, specially because our `OS` and `Apps` are desktop exclusive, no one planned code sharing or mobile responsiveness for them...

Of course we could use code sharing with `OS` / `Apps` code, but we're stuck with **this OOP-like architecture that couples state with messages**, this architecture is okay until you need to replicate that model somewhere else, like what `ServerGears` does, this is why Motherboard isn't a direct part of Hardware.

Our architecture is okay, it's scalable, but it wasn't planned to be DRY, and it's a PITA to get to this level of  flexibility from where we're now. And frankly imho 100% of reuse's not worth, specially 'cause most of our OS/Apps code is UI related (even if you only take the model)

But hey, at least we're able to share 100% of our Game code, that's a great feat :)

---

### Endpoint-only windows have no access to a gateway

> 2 - We used to pass "activeGateway" and we could pass "gateways" through configs to apps, why isn't this happening anymore?

Because the gateway that window want is hard to fetch, try to imagine that you need the gateway of the session that window came from, pinned windows brings all these edge cases.

Our main source of bad behaviour now comes from this situation where you're with a pinned `endpoint` only window from an `endpoint session`.

It's impossible to guess which gateway to pass unless we map `endpoints -> gateway` somewhere (probably `Game.Servers`).

---

### 3 - If you're sure that is the best way, OK!

I'm not sure what you meant.

**Comment by kress95** [comment]
### We're storing Applications at Game to avoid the "Game depends on OS" problem

I'll take recommended fixes and:

- Move `Core.Error` to `Utils.Error` or `Game.Error`.
- Move `Core.Flags` to `Game.Flags`.

### Endpoint-only windows have no access to a gateway

Note that my current solution covers every edge case but the **pinned `endpoint` only window from an `endpoint session`**, it's really the only situation this problem rises, so it should never be a problem if no endpoint-only app appears. 

### Adding apps is tedious again

Still a tedious but shouldn't be a problem as we're not going to add many new apps.

### I'm still not happy with our Launch.elm

I'll refactor that code again, it should be better this time: I fixed cyclic references on my model, so it should be simpler.

---

Yup, pretty much no depts, I'm happy again :)

**Comment by kress95** [comment]
I'm closing this as we have no endpoint-only apps, I've pinned this issue on discord as a warning.

**Comment by kress95** [comment]
> **Note:** I've decided to tackle the `endpoint -> gateway` mapping, and it greatly simplifies WM helpers file.
