### ISSUE TITLE
Endpoint context Apps is not rendering

### ISSUE THREAD

**Issue by themaxhero** [HackerExperience/HEBorn#477]
When change context from Gateway to Endpoint, and Try to open apps on Endpoint context for some reason apps become a empty window just like the attached screenshot.
![screenshot_20180308_214734](https://user-images.githubusercontent.com/4708337/37184568-b9b7fb02-231a-11e8-899d-b6a1c60dbdb3.png)

**Comment by kress95** [comment]
I proudly to announce that #481 fixed that :smile:
