### ISSUE TITLE
Processes Percentage is not working properly

### ISSUE THREAD

**Issue by themaxhero** [HackerExperience/HEBorn#479]
The Progress bar is being filled in 50% of the process completion.

**Comment by kress95** [comment]
Maybe it's a problem with the estimated completion date?

**Comment by themaxhero** [comment]
I don't think so, it looks like the Process.progress is not being modified.

**Comment by kress95** [comment]
I think it shouldn't, the bar changes according to lastTick and ETA.

**Comment by PedroHLC** [comment]
I solved this once, a long time ago
