### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Gamersialke** [HackerExperience/HEBorn#485]
I'm trying to login, but always there's a error that says "Login Failed". I'm writing the passes correctly, obviously checked that. It's my first logging in and i'm connecting from Poland, if it's important. 
And yes, i migrated account.

EDIT: I see that there's an error 
![image](https://user-images.githubusercontent.com/37382345/37426087-bbc706cc-27c5-11e8-8bcc-547594faeaff.png)

**Comment by firerex145** [comment]
I can’t login in either, but I’m using iOS firefox browser and I don’t know if I am getting the same error. I was able to login before though.

**Comment by Gamersialke** [comment]
EDIT: I checked the api.hackerexperience.com with isitdownrightnow and it showed that's the server is down

**Comment by Gamersialke** [comment]
@

**Comment by firerex145** [comment]
I see

**Comment by kress95** [comment]
Yup, looks like `api.hackerexperience.com` is down.

We're already taking initial actions to fix it (reporting to @renatomassaro, he's the one that deals with infrastructure).

Since this is not related to HEBorn **code** , I'm closing it down.
