### ISSUE TITLE
Weird window size for maximized windows

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#492]
Maximized window size is weird.

[https://imgur.com/a/dTvDr]!(https://imgur.com/a/dTvDr)

This is affecting both chrome and firefox.
I believe this is related to that change that applied limits for window sizes.

**Comment by PedroHLC** [comment]
I think this is the sidebar and the dock reserving theirs space

**Comment by kress95** [comment]
Probably, I don't like this behaviour, but maybe it's expected (or ok).

**Comment by PedroHLC** [comment]
It's mac-likish

**Comment by kress95** [comment]
Yeah, it's alright, this is more like an UX discussion than a bug.
