### ISSUE TITLE
Task Manager runtime exception on Chromium

### ISSUE THREAD

**Issue by kress95** [HackerExperience/HEBorn#493]
Task manager is causng this runtime exception on Chromium:

`Error: <polyline> attribute points: Expected number, "NaN,1".`

I believe we're having some compatibility issues with svg on webkit :cry:

> This is a known and early bug, we're forced to fix it now to run the game with electron.

**Comment by PedroHLC** [comment]
That's weird, why is there a NaN there?

**Comment by kress95** [comment]
I really don't know, but it's related to the taskmanager somehow, maybe the svg package is not compatible with chrome?

**Comment by PedroHLC** [comment]
Would be weird, the svg package is from elm-lang and its just a wrapper to elm-virtualdom, elm-html works identicaly
