### ISSUE TITLE
Rename `Context` to `Menu`

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/HEBorn#53]
With the addition of Context (local or remote) with #52, we need to replace all previous `Context` entries with `Menu` to make sure it does not get confusing.

**Comment by kress95** [comment]
I wanted to do this one, but it would break things for everyone.

**Comment by kress95** [comment]
I'm assuming `OS.Context` is also a menu and that `ContextMenu` won't need to be renamed.
