### ISSUE TITLE
Abstract View render logic

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/HEBorn#62]
So, here's an idea to make our dev flow easier.

Currently each object from the View, like any log entry or file entry, is hard-coded into the view itself. Try to abstract the act of loading the object from rendering (styling) it.

Example:

Instead of

```elm
            [ div [ class [ CntListEntry, EntryDir ] ]
                [ span [ class [ DirIcon ] ] []
                , span [] [ text "Downloads" ]
                ]
            , div [ class [ CntListEntry, EntryArchive ] ]
                [ span [ class [ VirusIcon ] ] []
                , span [] [ text "MyVirus.spam" ]
                , span [] [ text "2.3" ]
                , span [] [ text "230 MB" ]
                ]
            , div [ class [ CntListContainer ] ]
                [ div [ class [ CntListEntry, EntryArchive ] ]
                    [ span [ class [ FirewallIcon ] ] []
                    , span [] [ text "TheWall.fwl" ]
                    , span [] [ text "4.0" ]
                    , span [] [ text "230 MB" ]
                    ]
                , div [ class [ CntListChilds ] ]
                    [ div []
                        [ span [ class [ ActiveIcon ] ] []
                        , span [] [ text "Active" ]
                        , span [] [ text "4.5" ]
                        , span [] []
                        ]
                    , div []
                        [ span [ class [ PassiveIcon ] ] []
                        , span [] [ text "Passive" ]
                        , span [] [ text "3.5" ]
                        , span [] []
                        ]
                    ]
                ]
            ]
```

use something like

```elm

loadFiles model =
    -- files = (getFilesOnPath model)
    files = [file1, file2, file3]
    List.map renderFile files

renderFile file =
    div [ class [ CntListEntry, EntryArchive ] ]
        [ span [ class [ file.icon ] ]
        , span [] [ text file.name ]
    ]


viewExplorerMain model =
    renderHeader model
    renderEntries model

renderEntries model =
    div [ class [ ContentList ] ]
         [ loadFiles ]
l
```

Above code is wrong, but it's OK to get an idea of what I mean. In simpler words, make the View code generic.

The `List.map renderFiles files` is just a suggestion, you don't have to do exactly like this. Though it seems like the way to go. Probably the best way to get files on path is to use Filesystem's function `getFilesOnPath`.

By default your filesystem is empty, so if you want to add some dummy data, all you have to do is replace the original `files` list with `myMadeupFiles` or something like that.

I'm open to suggestions on how to improve this "pattern".

**Comment by kress95** [comment]
This is just function splitting (into helper functions) + function composition.

We're always doing that 😄 

The splitting should always be tackled on a case-by-case basis, we should split reusable code of giant functions, but no reason for splitting small functions.

I'll close this, okay?
-- 

> This comes from a long time ago when lisp programmers realized that big functions are bad and that > people should keep them small (very, very, very small like 20 lines functions are considered giant
> function)
