### ISSUE TITLE
Fuzzing found a bug

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/HEBorn#94]
Funny this happened after 5 or 6 *long* builds, so probably passed some 600 tests until it found this one :astonished: 

```
[Test] Running 39 tests. To reproduce these results, run: elm-test --seed 486670792
[Test]
[Test] ��� heborn
[Test] ��� filesystem
[Test] ��� file operations
[Test] ��� delete files
[Test] ��� delete folder
[Test] ��� folder path no longer exists
[Test]
[Test] Given 1389533003
[Test]
[Test] True
[Test] ���
[Test] ��� Expect.equal
[Test] ���
[Test] False
```
from [this build](https://ci.hackerexperience.com/job/HackerExperience/job/HEBorn/job/master/8/console)

**Comment by kress95** [comment]
I had this one before, fixed it and tried to reproduce it so many times but it didn't appeared again :/

this supposedly happens when it generates something not random enough, the I'll have to check what is not random enough this time...

**Comment by kress95** [comment]
Wait, the Gen update is not merged yet, so this problem may be fixed already (the current master doesn't use pcg for everything), let's check it.

**Comment by renatomassaro** [comment]
Yep, should be fixed after we merge those test PRs.
