### ISSUE TITLE
Max. number of opened windows of any application should be limited to no more than 2

### ISSUE THREAD

**Issue by xyx0826** [HackerExperience/HEBorn#99]
It is possible to click the app icons on the dock to spawn 32 windows of the same kind.
However these redundant windows are unnecessary since most windows will be having only 2 contexts (local, remote).
I suggest limiting allowed windows for any application to no more than 2. This can prevent unintended chaos on the UI.

**Comment by renatomassaro** [comment]
Even though you are correct that there are only two contexts (and some applications only have one, like Browser), there are some valid cases where you want three or more open windows.

Some examples:

- one Explorer window focused on local path A, another Explorer focused on local path B, and another Explorer on remote path C.
- one local LogViewer showing the newest entries and another local LogViewer showing my custom fancy query (filter)

I do agree that these are somewhat uncommon, or more "power user" scenarios, but I don't think we should set a hard-limit (or one as low as 2) for number of windows of same type open.

As for chaotic UI, I guess it's up to the user to have their own organization. Tools like "Close all" help them manage windows. In any case, I don't see any scenario where one would open 5+ windows of the same type, except when testing "hey, how many windows can I open?"

A limit of, say, 5 open windows could be enforced, but I don't see any actual benefit for this rather arbitrary limit.

**Comment by kress95** [comment]
I believe it should be limited, but not as a way to incentivate/enforce organization, organization is highly arbitrary, not a reason for such a change... on the other hand, breaking the UI is not cool.
